[package]
name = "shell-engine"
version = "0.2.5"
edition = "2024"
rust-version = "1.85"
license = "MIT"
readme = "README.md"
description = "An async shell runtime for persistent sessions, PTY I/O, output buffering, real-time callbacks, and screen snapshots."
repository = "https://github.com/ZEROLINGG/shell-engine"
documentation = "https://docs.rs/shell-engine"
homepage = "https://github.com/ZEROLINGG"
keywords = ["shell", "async", "pty", "subprocess", "terminal"]
categories = ["asynchronous", "command-line-interface"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["process", "io-util", "sync", "rt", "time", "macros"] }
serde = { version = "1", features = ["derive"] }

strip-ansi-escapes = "0.2"
encoding_rs = "0.8"

rust-pty = { version = "0.6", optional = true}
vt100 = { version = "0.16.2", optional = true}


[target.'cfg(windows)'.dependencies]
codepage = "0.1"

[features]
default = [
    "pty"
]
pty = [
    "dep:rust-pty",
    "dep:vt100"
]